name: psyc_fit
version: 0.0.1+1
description: Fitness App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
#  flutter_unity_widget: ^2022.1.7+1
  pointer_interceptor: ^0.9.3+2
  get_it: ^7.2.0
  # For state management
  bloc: ^8.0.1
  # Allows value based equality for our classes e.g Eat() == Eat() is true
  equatable: ^2.0.3
  # Generates code for us by providing annotations we can use
  injectable: ^1.5.3
  # Allows converting json to dart class and back
  json_annotation: ^4.4.0
  # Allows easier routing
  auto_route: ^5.0.1
  awesome_notifications: ^0.6.21
  permission_handler: ^10.1.0
  path_provider: ^2.0.11
  google_sign_in: ^5.4.2

  objectbox: ^1.6.2
  objectbox_flutter_libs: any
  font_awesome_flutter: ^10.2.1
  hexcolor: ^2.0.4
  http: ^0.13.5

  firebase_core: ^1.21.1
  firebase_crashlytics: ^2.8.9
  firebase_analytics: ^9.3.3
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  firebase_messaging: ^13.0.0
  firebase_remote_config: ^2.0.16
#  firebase_performance: ^0.8.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner: ^2.2.0
  auto_route_generator: ^5.0.1
  json_serializable: ^6.1.3
  bloc_test: ^9.0.1
  mockito: ^5.3.0
  flutter_launcher_icons: ^0.9.2
  objectbox_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/exercise.json
    - assets/login.jpg
    - assets/tick.png
    - assets/avatars/avatar-1.jpg
    - assets/avatars/avatar-2.jpg
    - assets/avatars/avatar-3.jpg
    - assets/avatars/avatar-4.jpg
    - assets/avatars/avatar-5.jpg
    - assets/avatars/avatar-6.jpg
    - assets/avatars/default-avatar.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
